#!/bin/bash

# for ack config, see ~/.ackrc

ack "$@"

exit $?;

######### ag misses stuff... by design

ag "$@"

exit $?

######################################

echo "use ack and .ackrc instead"
exit

######################################

TERM="$1"
DIR=${2:-.}
set -x
grep -r --color --text "$TERM" $DIR \
| egrep --text -v 'blib|\.git'      \
| grep --color --text "$TERM"

#| egrep --text -v '\.js|\.css'      \
#| egrep --text -v '/local/'         \
