#!/bin/bash

# Quickly check the syntax of perl modules you've just modified

BRANCH="$1"

for module in `git diff $BRANCH --stat=200,200|grep '.pm '|perl -lane'print$F[0]'|tac`
do
    perl -Mdiagnostics -c -I lib -I t/lib $module
done
