#!/bin/bash

# change the author of a ramge of commits
# by default every commit on a branch changes
# you can choose the start commit,
# but the end commit will always be HEAD
# for more control, see https://stackoverflow.com/a/15265846/137948

git filter-branch --commit-filter 'if [ "$GIT_AUTHOR_NAME" = "Will Sheppard" ]; then
    export GIT_AUTHOR_NAME="Will Sheppard";
    export GIT_AUTHOR_EMAIL=nobody@example.com;
    export GIT_COMMITTER_NAME="Will Sheppard";
    export GIT_COMMITTER_EMAIL=nobody@example.com;
fi;
git commit-tree "$@"'
