#!/bin/bash

# Display a visual divider
perl -le'$tr = ("=") x 120; print $tr for 1..2'

# Diff with useful options
#git diff -b --relative --color --histogram $@
git diff --no-prefix --relative --color --histogram $@

echo

git status
