#!/bin/bash

if [[ -z "$branch" ]]
    echo "\$branch must be set to the current branch"
    exit
fi

echo .
echo "Are you sure? This will WIPE your current local commits,"
read -p "and replace them with whatever is at ORIGIN! ... "

# back up to the stash in case of accident
git stash save $branch"_backup_"$(date +"%F_%H-%M-%S")
    # Disabled branch backup as it results in a lot of unused branches
#git branch $branch"_backup_"$(date +"%F_%H-%M-%S")

git remote update
git fetch

echo .
echo "type it yourself:"
echo
echo "git reset --hard origin/$branch"
echo .

#git reset --hard origin/$branch
