#!/usr/bin/perl

# highlight search terms

select STDERR; $| = 1;
select STDOUT; $| = 1;

use Term::ANSIColor;

my $term = $ARGV[0] or die "usage: hi regex [color] [whole line?]\n";
my $color = $ARGV[1] // "red";
my $line = $ARGV[2] // 0;

while (my $c = <STDIN>) {
    if ($line) {
        if ($c =~ /($term)/) {
            print color($color).$c.color("reset");
        }
        else {
            print $c;
        }
    } else {
        $c =~ s/($term)/color($color).$1.color("reset")/eig;
        print $c;
    }
}
