#!/usr/bin/env perl

# SETUP

use strict;
use warnings;

my $debug = 0;

my @vowel     = (qw/ a e i o u /);                              print '@vowel = '    .join(', ',@vowel)    ."\n" if $debug;
my @not_vowel = (qw/ q w r t y p s d f g h k z x c v b n m /);  print '@not_vowel = '.join(', ',@not_vowel)."\n" if $debug;
my @numba     = (qw/ 2 3 4 5 6 7 8 9 /);                        print '@numba = '    .join(', ',@numba)    ."\n" if $debug;
 
# MAIN

my @password = (
    con(),
    vow(),
    con(),
#    con(),
    num(),
    num(),
    con(),
    vow(),
    con(),
#    con(),
);
print join('',@password)."\n";

exit;


# FUNCTIONS

sub vow { _choose(\@vowel) }
sub con { _choose(\@not_vowel) }
sub num { _choose(\@numba) }

sub _choose {
    my ($list) = (@_);
    my $choice = $list->[ rand @$list ];
    print "choice = $choice\n" if $debug;
    return $choice;
}

