#!/bin/bash

# strict mode
set -euo pipefail
IFS=$'\n\t'

PACKAGES="
ruby
perl
python3
nginx
youtube-dl
ffmpeg
"

echo "Packages:" $PACKAGES
read -r -p "Are you sure you want to install? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
	echo "Very well, continuing box initialisation..."
        ;;
    *)
	echo "Aborted."
	exit 1
        ;;
esac

sleep 5

set -vx

for package in $PACKAGES; do
    sudo apt -y install $package
done
