#!/bin/bash

# strict mode
set -euo pipefail
IFS=$'\n\t'

read -r -p "Are you sure this is a new box without anything on it yet? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
	echo "Very well, continuing box initialisation..."
        ;;
    *)
	echo "Aborted."
	exit 1
        ;;
esac

sleep 5

set -vx

mkdir -p ~/dev
cd ~/dev
git clone https://github.com/willsheppard/send-me-motd.git
git clone https://github.com/willsheppard/misc-config.git
git clone https://github.com/willsheppard/linux-scripts
git clone https://github.com/willsheppard/dotfiles.git
git clone https://github.com/willsheppard/rfobasic.git
git clone https://github.com/willsheppard/stuff-and-things.git
git clone https://github.com/willsheppard/college-pascal.git
git clone https://github.com/willsheppard/ruby-koans-exercises.git
git clone https://github.com/willsheppard/learning-ruby.git
git clone https://github.com/willsheppard/python_koans.git

cd ~
echo "" >> .bashrc
echo "# WS custom setup" >> .bashrc
echo "source ~/dev/dotfiles/.bashrc" >> .bashrc
ln -s dev/dotfiles/.gitconfig .gitconfig
ln -s dev/dotfiles/.vimrc .vimrc

